// <auto-generated />
using System;
using LTSMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LTSMVC.Migrations
{
    [DbContext(typeof(ltsContext))]
    [Migration("20201202194521_initialD")]
    partial class initialD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LTSMVC.Models.Account", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("idStaff");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("account_type")
                        .UseCollation("utf32_bin")
                        .HasCharSet("utf32");

                    b.Property<string>("AddInfo")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("add_info")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("login")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<DateTime?>("OutDate")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("out_date");

                    b.Property<string>("Pass")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("pass")
                        .UseCollation("utf32_bin")
                        .HasCharSet("utf32");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "Id_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "StaffId" }, "fk_account_staff1_idx");

                    b.ToTable("account");
                });

            modelBuilder.Entity("LTSMVC.Models.AddressBook", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<int?>("IpNumber")
                        .HasColumnType("int")
                        .HasColumnName("Ipnumber");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int")
                        .HasColumnName("Phonenumber");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("place")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("post")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Sld")
                        .HasColumnType("char(2)")
                        .HasColumnName("SLD")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short?>("StaffId")
                        .HasColumnType("smallint")
                        .HasColumnName("StaffId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StaffId" }, "fk_Num_table_staff1_idx");

                    b.ToTable("address_book");
                });

            modelBuilder.Entity("LTSMVC.Models.Expendable", b =>
                {
                    b.Property<ushort>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("Id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("expendables");
                });

            modelBuilder.Entity("LTSMVC.Models.ExpendablesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<ushort>("ExpendablesId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("ExpendablesId");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint")
                        .HasColumnName("StafId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(35)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpendablesId" }, "fk_Expendables_items_Expendables1_idx");

                    b.HasIndex(new[] { "StaffId" }, "fk_Expendables_items_staff1_idx");

                    b.ToTable("ExpendablesItems");
                });

            modelBuilder.Entity("LTSMVC.Models.JournalExpendable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("ExpendablesItemsId")
                        .HasColumnType("int")
                        .HasColumnName("ExpendablesItemsId");

                    b.Property<string>("State")
                        .HasColumnType("varchar(900)")
                        .HasColumnName("state")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("time");

                    b.Property<int?>("TrigerUser")
                        .HasColumnType("int")
                        .HasColumnName("TrigerUser");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ExpendablesItemsId" }, "fk_journal_Expendables_Expendables_items1_idx");

                    b.ToTable("journal_expendables");
                });

            modelBuilder.Entity("LTSMVC.Models.JournalMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<short>("MachinesId")
                        .HasColumnType("smallint")
                        .HasColumnName("MachinesId");

                    b.Property<string>("State")
                        .HasColumnType("varchar(2000)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("timestamp(6)");

                    b.Property<int?>("TrigerUser")
                        .HasColumnType("int")
                        .HasColumnName("TrigerUser");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MachinesId" }, "fk_Journal_Machines_Machines1_idx");

                    b.ToTable("journal_machines");
                });

            modelBuilder.Entity("LTSMVC.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtLicense");

                    b.Property<string>("Lisence")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("MachinesId")
                        .HasColumnType("smallint")
                        .HasColumnName("MachinesId");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint")
                        .HasColumnName("StaffId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MachinesId" }, "fk_License_Machines1_idx");

                    b.HasIndex(new[] { "StaffId" }, "fk_License_staff1_idx");

                    b.ToTable("license");
                });

            modelBuilder.Entity("LTSMVC.Models.Machine", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("Id");

                    b.Property<string>("AddInfo")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("add_info")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Charecter")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("charecter")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Expendables")
                        .HasColumnType("varchar(300)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("InvNumber")
                        .IsRequired()
                        .HasColumnType("char(13)")
                        .HasColumnName("inv_number")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short?>("LastUser")
                        .HasColumnType("smallint")
                        .HasColumnName("LastUser");

                    b.Property<string>("Mod")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mod")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(30)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint")
                        .HasColumnName("Staffid");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("'Склад'")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("type")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "Id" }, "fk_Machines_staff_index");

                    b.HasIndex(new[] { "Id" }, "id_Machines_UNIQUE")
                        .IsUnique();

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("LTSMVC.Models.MachinesConnect", b =>
                {
                    b.Property<short>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("idMachines_connect");

                    b.Property<sbyte?>("IsAdmin")
                        .HasColumnType("tinyint")
                        .HasColumnName("Is_Admin");

                    b.Property<string>("Login")
                        .HasColumnType("varchar(15)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("MachinesId")
                        .HasColumnType("smallint")
                        .HasColumnName("Machines_id");

                    b.Property<string>("Pass")
                        .HasColumnType("varchar(16)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MachinesId" }, "fk_Machines_connect_Machines1_idx");

                    b.ToTable("machines_connect");
                });

            modelBuilder.Entity("LTSMVC.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp(6)");

                    b.Property<short>("FromUser")
                        .HasColumnType("smallint")
                        .HasColumnName("FromUser");

                    b.Property<sbyte>("IsOnlyFile")
                        .HasColumnType("tinyint")
                        .HasColumnName("is_only_file");

                    b.Property<short>("ToUser")
                        .HasColumnType("smallint")
                        .HasColumnName("ToUser");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("LTSMVC.Models.MessageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMessage_file");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Data_type")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("Messages_idMessage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MessageId" }, "fk_Message_File_Messages1_idx");

                    b.ToTable("message_file");
                });

            modelBuilder.Entity("LTSMVC.Models.MessageText", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Messages_idMessage");

                    b.Property<string>("Text")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Message_text")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasIndex(new[] { "Id" }, "fk_Message_text_Messages1_idx");

                    b.ToTable("message_text");
                });

            modelBuilder.Entity("LTSMVC.Models.NetworkAdress", b =>
                {
                    b.Property<string>("AddressType")
                        .HasColumnType("char(1)")
                        .HasColumnName("Address_type")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<short?>("IpAdress")
                        .HasColumnType("smallint")
                        .HasColumnName("Ip_Adress");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("varchar(17)")
                        .HasColumnName("MAC")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short?>("MachinesId")
                        .HasColumnType("smallint")
                        .HasColumnName("Machines_id_Machines");

                    b.Property<short>("Network")
                        .HasColumnType("smallint");

                    b.HasIndex(new[] { "MachinesId" }, "fk_Network_adress_Machines1_idx");

                    b.ToTable("network_adress");
                });

            modelBuilder.Entity("LTSMVC.Models.RemoveControl", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("idconnected_machines");

                    b.Property<string>("AmmyAdmin")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Ammy_Admin")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("AmmyAdminPass")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Ammy_Admin_pass")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("AnyDesk")
                        .HasColumnType("varchar(10)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("AnyDeskPass")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AnyDesk_pass")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<short>("MachinesId")
                        .HasColumnType("smallint")
                        .HasColumnName("Machines_id");

                    b.Property<string>("Rdp")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rdp")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("TeamViewer")
                        .HasColumnType("varchar(10)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("TeamViewerPass")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TeamViewer_pass")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MachinesId" }, "fk_connected_machines_Machines1_idx");

                    b.ToTable("remove_control");
                });

            modelBuilder.Entity("LTSMVC.Models.Staff", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("Staff_id");

                    b.Property<bool>("AdminU")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("admin_u");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("place")
                        .UseCollation("utf32_bin")
                        .HasCharSet("utf32");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Staff_Name")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("StaffPoss")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Staff_Poss")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("StaffSub")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Staff_Sub")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<int>("TgId")
                        .HasColumnType("int")
                        .HasColumnName("tg_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "Staff_id_3")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ticket");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("Date_close");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("Date_open");

                    b.Property<short>("StaffId")
                        .HasColumnType("smallint")
                        .HasColumnName("Staff");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("TicketProblem")
                        .HasColumnType("varchar(500)")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StaffId" }, "fk_chat_staff1_idx");

                    b.ToTable("ticket");
                });

            modelBuilder.Entity("LTSMVC.Models.TicketFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_message_file");

                    b.Property<string>("DataType")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("data_type")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8_general_ci")
                        .HasCharSet("utf8");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("Ticket_id_ticket");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TicketId" }, "fk_ticket_file_Ticket1_idx");

                    b.ToTable("ticket_file");
                });

            modelBuilder.Entity("LTSMVC.Models.Account", b =>
                {
                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("Accounts")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_account_staff1")
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.AddressBook", b =>
                {
                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("AddressBooks")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_Num_table_staff1");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.ExpendablesItem", b =>
                {
                    b.HasOne("LTSMVC.Models.Expendable", "Expendables")
                        .WithMany("ExpendablesItems")
                        .HasForeignKey("ExpendablesId")
                        .HasConstraintName("fk_Expendables_items_Expendables1")
                        .IsRequired();

                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("ExpendablesItems")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_Expendables_items_staff1")
                        .IsRequired();

                    b.Navigation("Expendables");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.JournalExpendable", b =>
                {
                    b.HasOne("LTSMVC.Models.ExpendablesItem", "ExpendablesItems")
                        .WithMany("JournalExpendables")
                        .HasForeignKey("ExpendablesItemsId")
                        .HasConstraintName("fk_journal_Expendables_Expendables_items1")
                        .IsRequired();

                    b.Navigation("ExpendablesItems");
                });

            modelBuilder.Entity("LTSMVC.Models.JournalMachine", b =>
                {
                    b.HasOne("LTSMVC.Models.Machine", "Machine")
                        .WithMany("JournalMachines")
                        .HasForeignKey("MachinesId")
                        .HasConstraintName("fk_Journal_Machines_Machines1")
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("LTSMVC.Models.License", b =>
                {
                    b.HasOne("LTSMVC.Models.Machine", "Machine")
                        .WithMany("Licenses")
                        .HasForeignKey("MachinesId")
                        .HasConstraintName("fk_License_Machines1")
                        .IsRequired();

                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("Licenses")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_License_staff1")
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.Machine", b =>
                {
                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("Machines")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_Machines_staff")
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.MachinesConnect", b =>
                {
                    b.HasOne("LTSMVC.Models.Machine", "Machines")
                        .WithMany("MachinesConnects")
                        .HasForeignKey("MachinesId")
                        .HasConstraintName("fk_Machines_connect_Machines1")
                        .IsRequired();

                    b.Navigation("Machines");
                });

            modelBuilder.Entity("LTSMVC.Models.MessageFile", b =>
                {
                    b.HasOne("LTSMVC.Models.Message", "Message")
                        .WithMany("MessageFiles")
                        .HasForeignKey("MessageId")
                        .HasConstraintName("fk_Message_File_Messages1")
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LTSMVC.Models.MessageText", b =>
                {
                    b.HasOne("LTSMVC.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_Message_text_Messages1")
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("LTSMVC.Models.NetworkAdress", b =>
                {
                    b.HasOne("LTSMVC.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachinesId")
                        .HasConstraintName("fk_Network_adress_Machines1");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("LTSMVC.Models.RemoveControl", b =>
                {
                    b.HasOne("LTSMVC.Models.Machine", "Machines")
                        .WithMany("RemoveControls")
                        .HasForeignKey("MachinesId")
                        .HasConstraintName("fk_connected_machines_Machines1")
                        .IsRequired();

                    b.Navigation("Machines");
                });

            modelBuilder.Entity("LTSMVC.Models.Ticket", b =>
                {
                    b.HasOne("LTSMVC.Models.Staff", "Staff")
                        .WithMany("Tickets")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("fk_chat_staff1")
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LTSMVC.Models.TicketFile", b =>
                {
                    b.HasOne("LTSMVC.Models.Ticket", "Ticket")
                        .WithMany("TicketFiles")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("fk_ticket_file_Ticket1")
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("LTSMVC.Models.Expendable", b =>
                {
                    b.Navigation("ExpendablesItems");
                });

            modelBuilder.Entity("LTSMVC.Models.ExpendablesItem", b =>
                {
                    b.Navigation("JournalExpendables");
                });

            modelBuilder.Entity("LTSMVC.Models.Machine", b =>
                {
                    b.Navigation("JournalMachines");

                    b.Navigation("Licenses");

                    b.Navigation("MachinesConnects");

                    b.Navigation("RemoveControls");
                });

            modelBuilder.Entity("LTSMVC.Models.Message", b =>
                {
                    b.Navigation("MessageFiles");
                });

            modelBuilder.Entity("LTSMVC.Models.Staff", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AddressBooks");

                    b.Navigation("ExpendablesItems");

                    b.Navigation("Licenses");

                    b.Navigation("Machines");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("LTSMVC.Models.Ticket", b =>
                {
                    b.Navigation("TicketFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
